#include "asm_codegen.hpp"
#include "ast_printer.hpp"
#include "bytecode.hpp"
#include "codegen.hpp"
#include "error.hpp"
#include "lexer.hpp"
#include "parser.hpp"
#include "semantic.hpp"
#include "vm.hpp"

#include <chrono>
#include <fstream>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>

using namespace minilang;

static Result<std::string> readFile(const std::string& path) {
    std::ifstream file(path);

    if (!file) {
        return std::unexpected(
            Diagnostic(SourceLocation(), "cannot open file: " + path)
        );
    }

    std::ostringstream buffer;
    buffer << file.rdbuf();

    return buffer.str();
}

static Result<std::string> readStandardLibrary() {
    const char* paths[] = {
        "stdlib/prelude.ml",
        "stdlib/io.ml",
        "stdlib/math.ml",
        "stdlib/string.ml",
        "stdlib/array.ml",
        "stdlib/memory.ml",
    };

    std::ostringstream buffer;

    for (const char* path : paths) {
        Result<std::string> part = readFile(path);

        if (!part) {
            return std::unexpected(
                Diagnostic(
                    SourceLocation(),
                    "cannot load standard library file '" +
                    std::string(path) +
                    "': " +
                    part.error().message
                )
            );
        }

        buffer << "\n";
        buffer << *part;
        buffer << "\n";
    }

    return buffer.str();
}

static double millisecondsSince(std::chrono::steady_clock::time_point start,
                                std::chrono::steady_clock::time_point end) {
    return std::chrono::duration<double, std::milli>(end - start).count();
}

static void printPhaseTime(const std::string& name, double milliseconds) {
    std::cerr << "[time] " << name << ": " << milliseconds << " ms" << std::endl;
}

static void printUsage() {
    std::cout
        << "Usage: minilang <source-file> [-o <output-file>] [options]\n"
        << "\n"
        << "Options:\n"
        << "  -o <file>         set output file name for future native backend\n"
        << "  --dump-tokens     print lexer tokens and exit\n"
        << "  --dump-ast        print AST and exit\n"
        << "  --dump-bytecode   print generated bytecode\n"
        << "  --emit-asm        generate x86-64 NASM assembly and exit\n"
        << "  --no-run          compile only, do not run VM\n"
        << "  --time-phases     print time spent in compiler phases\n"
        << "  --use-stdlib      prepend MiniLangVM standard library files\n"
        << "  --help            show this help message\n";
}

static Result<void> dumpTokens(const std::string& source) {
    Lexer lexer(source);

    while (true) {
        Result<Token> tokenResult = lexer.nextTokenExpected();

        if (!tokenResult) {
            return std::unexpected(tokenResult.error());
        }

        Token token = *tokenResult;

        std::cout << tokenToString(token) << std::endl;

        if (token.type == TokenType::EndOfFile) {
            break;
        }
    }

    return {};
}

int main(int argc, char** argv) {
    std::string sourcePath;
    std::string outputPath;

    bool shouldDumpTokens = false;
    bool shouldDumpAst = false;
    bool shouldDumpBytecode = false;
    bool shouldEmitAsm = false;
    bool shouldRun = true;
    bool shouldTimePhases = false;
    bool shouldUseStdlib = false;

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];

        if (arg == "--help") {
            printUsage();
            return 0;
        }

        if (arg == "--dump-tokens") {
            shouldDumpTokens = true;
            continue;
        }

        if (arg == "--dump-ast") {
            shouldDumpAst = true;
            continue;
        }

        if (arg == "--dump-bytecode") {
            shouldDumpBytecode = true;
            continue;
        }

        if (arg == "--emit-asm") {
            shouldEmitAsm = true;
            shouldRun = false;
            continue;
        }

        if (arg == "--no-run") {
            shouldRun = false;
            continue;
        }

        if (arg == "--time-phases") {
            shouldTimePhases = true;
            continue;
        }

        if (arg == "--use-stdlib") {
            shouldUseStdlib = true;
            continue;
        }

        if (arg == "-o") {
            if (i + 1 >= argc) {
                std::cerr << "<command-line>:1:1: error: expected output file after -o" << std::endl;
                return 1;
            }

            outputPath = argv[++i];
            continue;
        }

        if (!arg.empty() && arg[0] == '-') {
            std::cerr << "<command-line>:1:1: error: unknown option '" << arg << "'" << std::endl;
            return 1;
        }

        if (!sourcePath.empty()) {
            std::cerr << "<command-line>:1:1: error: multiple source files are not supported" << std::endl;
            return 1;
        }

        sourcePath = arg;
    }

    if (sourcePath.empty()) {
        printUsage();
        return 1;
    }

    (void)outputPath;

    auto totalStart = std::chrono::steady_clock::now();

    try {
        auto readStart = std::chrono::steady_clock::now();
        Result<std::string> sourceResult = readFile(sourcePath);
        auto readEnd = std::chrono::steady_clock::now();

        if (shouldTimePhases) {
            printPhaseTime("read", millisecondsSince(readStart, readEnd));
        }

        if (!sourceResult) {
            const Diagnostic& diagnostic = sourceResult.error();

            std::cerr << sourcePath
                      << ":" << diagnostic.location.line
                      << ":" << diagnostic.location.column
                      << ": error: "
                      << diagnostic.message
                      << std::endl;

            return 1;
        }

        std::string source = *sourceResult;

        if (shouldUseStdlib) {
            auto stdlibStart = std::chrono::steady_clock::now();
            Result<std::string> stdlibResult = readStandardLibrary();
            auto stdlibEnd = std::chrono::steady_clock::now();

            if (shouldTimePhases) {
                printPhaseTime("read-stdlib", millisecondsSince(stdlibStart, stdlibEnd));
            }

            if (!stdlibResult) {
                const Diagnostic& diagnostic = stdlibResult.error();

                std::cerr << sourcePath
                          << ":" << diagnostic.location.line
                          << ":" << diagnostic.location.column
                          << ": error: "
                          << diagnostic.message
                          << std::endl;

                return 1;
            }

            source += "\n";
            source += *stdlibResult;
        }

        if (shouldDumpTokens) {
            Result<void> dumpResult = dumpTokens(source);

            if (!dumpResult) {
                const Diagnostic& diagnostic = dumpResult.error();

                std::cerr << sourcePath
                          << ":" << diagnostic.location.line
                          << ":" << diagnostic.location.column
                          << ": error: "
                          << diagnostic.message
                          << std::endl;

                return 1;
            }

            if (shouldTimePhases) {
                auto totalEnd = std::chrono::steady_clock::now();
                printPhaseTime("total", millisecondsSince(totalStart, totalEnd));
            }

            return 0;
        }

        Lexer lexer(source);
        Parser parser(lexer);

        auto parseStart = std::chrono::steady_clock::now();
        Result<std::unique_ptr<Program>> parseResult = parser.parseProgramExpected();
        auto parseEnd = std::chrono::steady_clock::now();

        if (shouldTimePhases) {
            printPhaseTime("lex+parse", millisecondsSince(parseStart, parseEnd));
        }

        if (!parseResult) {
            const Diagnostic& diagnostic = parseResult.error();

            std::cerr << sourcePath
                      << ":" << diagnostic.location.line
                      << ":" << diagnostic.location.column
                      << ": error: "
                      << diagnostic.message
                      << std::endl;

            return 1;
        }

        std::unique_ptr<Program> program = std::move(*parseResult);

        SemanticAnalyzer semantic;
        auto semanticStart = std::chrono::steady_clock::now();
        Result<void> semanticResult = semantic.analyzeExpected(*program);
        auto semanticEnd = std::chrono::steady_clock::now();

        if (shouldTimePhases) {
            printPhaseTime("semantic", millisecondsSince(semanticStart, semanticEnd));
        }

        if (!semanticResult) {
            const Diagnostic& diagnostic = semanticResult.error();

            std::cerr << sourcePath
                      << ":" << diagnostic.location.line
                      << ":" << diagnostic.location.column
                      << ": error: "
                      << diagnostic.message
                      << std::endl;

            return 1;
        }

        if (shouldDumpAst) {
            AstPrinter printer;
            printer.print(*program, std::cout);

            if (shouldTimePhases) {
                auto totalEnd = std::chrono::steady_clock::now();
                printPhaseTime("total", millisecondsSince(totalStart, totalEnd));
            }

            return 0;
        }

        if (shouldEmitAsm) {
            if (outputPath.empty()) {
                outputPath = "out.asm";
            }

            AsmGenerator asmGenerator;

            auto asmStart = std::chrono::steady_clock::now();
            Result<void> asmResult = asmGenerator.generateExpected(*program, outputPath);
            auto asmEnd = std::chrono::steady_clock::now();

            if (shouldTimePhases) {
                printPhaseTime("asm-codegen", millisecondsSince(asmStart, asmEnd));
            }

            if (!asmResult) {
                const Diagnostic& diagnostic = asmResult.error();

                std::cerr << sourcePath
                          << ":" << diagnostic.location.line
                          << ":" << diagnostic.location.column
                          << ": error: "
                          << diagnostic.message
                          << std::endl;

                return 1;
            }

            if (shouldTimePhases) {
                auto totalEnd = std::chrono::steady_clock::now();
                printPhaseTime("total", millisecondsSince(totalStart, totalEnd));
            }

            return 0;
        }

        BytecodeGenerator generator;
        auto codegenStart = std::chrono::steady_clock::now();
        Result<Bytecode> bytecodeResult = generator.generateExpected(*program);
        auto codegenEnd = std::chrono::steady_clock::now();

        if (shouldTimePhases) {
            printPhaseTime("bytecode-codegen", millisecondsSince(codegenStart, codegenEnd));
        }

        if (!bytecodeResult) {
            const Diagnostic& diagnostic = bytecodeResult.error();

            std::cerr << sourcePath
                      << ":" << diagnostic.location.line
                      << ":" << diagnostic.location.column
                      << ": error: "
                      << diagnostic.message
                      << std::endl;

            return 1;
        }

        Bytecode bytecode = std::move(*bytecodeResult);

        if (shouldDumpBytecode) {
            std::cout << bytecodeToString(bytecode);

            if (!shouldRun) {
                if (shouldTimePhases) {
                    auto totalEnd = std::chrono::steady_clock::now();
                    printPhaseTime("total", millisecondsSince(totalStart, totalEnd));
                }

                return 0;
            }
        }

        if (!shouldRun) {
            if (shouldTimePhases) {
                auto totalEnd = std::chrono::steady_clock::now();
                printPhaseTime("total", millisecondsSince(totalStart, totalEnd));
            }

            return 0;
        }

        auto vmStart = std::chrono::steady_clock::now();

        VM vm;
        int exitCode = vm.run(bytecode);

        auto vmEnd = std::chrono::steady_clock::now();

        if (shouldTimePhases) {
            printPhaseTime("vm", millisecondsSince(vmStart, vmEnd));

            auto totalEnd = std::chrono::steady_clock::now();
            printPhaseTime("total", millisecondsSince(totalStart, totalEnd));
        }

        return exitCode;
    } catch (const MiniLangError& error) {
        SourceLocation loc = error.location();

        if (error.kind() == "runtime") {
            std::cerr << "runtime error: "
                      << error.message()
                      << " at line "
                      << loc.line
                      << std::endl;
        } else {
            std::cerr << sourcePath
                      << ":" << loc.line
                      << ":" << loc.column
                      << ": error: "
                      << error.message()
                      << std::endl;
        }

        return 1;
    } catch (const std::exception& error) {
        std::cerr << sourcePath
                  << ":1:1: error: "
                  << error.what()
                  << std::endl;

        return 1;
    }
}
